### BUSCAR FILMES

GET https://att-1-filmes.vercel.app/


### CADASTRAR FILME

POST http://localhost:3333/create
Content-Type: application/json

{
    "title": "Homem-Aranha: Sem Volta Pra Casa",
    "gender": "Ação",
    "ageLimit": 12,
    "duration": 149
}


### DELETAR FILME

DELETE http://localhost:3333/delete/12


### EDITAR FILME

PUT http://localhost:3333/update/2
Content-Type: application/json

{
    "title": "Senhor dos Anéis: As Duas Torres",
    "gender": "Fantasia / Ação",
    "ageLimit": 18,
    "duration": 187
}
